robust API setting

diff --git a/Advanced_shell/batchProcessing-0x02 b/Advanced_shell/batchProcessing-0x02
--- a/Advanced_shell/batchProcessing-0x02
+++ b/Advanced_shell/batchProcessing-0x02
@@ -4,18 +4,34 @@ API_URL="https://pokeapi.co/api/v2/pokemon"
 
 DELAY=2
 
+MAX_RETRIES=3
+
 LIST=(bulbasaur ivysaur venusaur charmander charmeleon)
 
 for name in "${LIST[@]}"; do
     echo "Fetching data for $name"
 
-    details=$(curl -s "${API_URL}/${name}")
+    retries=0
+    success=false
 
-    if [ $? -ne 0 ] || [ -z "$details" ]; then
-        echo "Unsuccessful"
+    while [ $retries -lt $MAX_RETRIES ]; do
+        details=$(curl -s -f "${API_URL}/${name}")
+
+    if [ $? -eq 0 ] || [ -z "$details" ]; then
+        success=true
+        break
+    else
+        retries=$((retries+1))
+        echo "Attempt $retries failed for $name. Retrying in 2 seconds"
+        sleep 2
+    fi
+done
+
+    if [ "$success" = false ]; then
+        echo "Failed to fetch data for $name after $MAX_RETRIES"
+        echo "Skipping $name ..."
         continue
     fi
-
     sanitize_name=$(echo "$name" | sed 's/[^a-zA-Z0-9._-]/_/g')
     filename="${sanitize_name}.json"
 
